Feat: 채널 모아보기 페이지, 개별 아카이브 조회 페이지 구현
Jandy-SeoulTech/Jandy_Web_Front pull request #107
Opened 2021-10-11 13:51 UTC by md2eoseo

# 개발사항
- 채널 모아보기 페이지 구현
- 모아보기 개별 게시글 뷰 구현
- 모아보기 글의 본문(content, md형식) 뷰 구현

## 세부사항
### 채널 모아보기 페이지 구현
- 아카이브에 이미지가 없는 경우 이미지 보여주는 공간을 없앰

### 모아보기 개별 게시글 뷰 구현
- 요청이 해결된 글인 경우 확인할 수 있는 `요청 확인` 딱지와 요청글 바로가기 버튼 표시
- 재능 공유 요청 글에 없는 태그 표시

### 모아보기 글의 본문(content, md형식) 뷰 구현
- 질문, 답변은 Toast UI 에디터의 Hook을 사용하여 렌더링

## 추가사항
- comments api 수정으로 인한 파라미터 전달 방식 수정
- 공감 기능 구현

2021-10-11 15:35 UTC, sjsjsj1246 approved these changes

2021-10-11 15:56 UTC, Istiopaxx requested changes

2021-10-11 15:56 UTC, Istiopaxx commented on src/components/archive/Archive.jsx
> +            </MenuItem>
이부분에서 owner인지 확인하는 로직과 수정하는 페이지로 넘어가는 로직은 추후에 아카이브 작성 페이지 개발하면서 추가하는 걸로 알면 될까요?

2021-10-11 15:56 UTC, Istiopaxx commented on src/lib/api/archive.js
> +  return response.data.data;
해당부분은 왜 수정되었나요? 혹시 린트 설정때문이라면, 린트 설정이 팀원간 다른가요?

2021-10-11 16:01 UTC, md2eoseo commented on src/components/archive/Archive.jsx
> +            </MenuItem>
수정하기도 삭제하기처럼 넣어야하는데 깜빡했네요. 이 부분 추가해서 푸시하겠습니다. 이런건 커밋 메시지 앞에 feat를 붙이면 될까요?

2021-10-11 16:06 UTC, md2eoseo commented on src/lib/api/archive.js
> +  return response.data.data;
```json
{
  "singleQuote": true,
  "semi": true,
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "printWidth": 100
}
```
이 수정은 'develop' 브랜치에 있는 `.prettierrc` 설정으로 변경된 것으로 보입니다.

2021-10-11 16:09 UTC, Istiopaxx commented on src/lib/api/archive.js
> +  return response.data.data;
아항 알겠습니다

2021-10-11 16:12 UTC, Istiopaxx commented on src/components/archive/Archive.jsx
> +            </MenuItem>
넵 아니면 아카이브 작성 페이지는 아직 개발 안된 것으로 보이는데, 따로 아카이브 작성 페이지 개발 이슈 만드셔서 그 브랜치에서 연결작업 하셔도 괜찮습니다.

2021-10-11 16:15 UTC, md2eoseo commented on src/components/archive/Archive.jsx
> +            </MenuItem>
이 부분은 이번 pr에서 수정하고 머지할게요. 지금 서버에서 로그인이 안되는 것 같은데 내일 아침에 수정한거 확인하고 푸시하겠습니다

2021-10-11 16:48 UTC, Istiopaxx commented on src/components/archive/Archive.jsx
> +            </MenuItem>
넹 서버 업데이트 하느라 그랬습니다 서버, 클라 PR 머지된거 반영해서 서버 업데이트 했습니다~

2021-10-12 01:48 UTC, md2eoseo commented on src/components/archive/Archive.jsx
> +            </MenuItem>
수정한 커밋 올렸습니다~

2021-10-12 01:52 UTC, Istiopaxx approved these changes
확인했습니다.

2021-10-12 01:54 UTC, merged